### ISSUE TITLE
Remove Arco

### ISSUE THREAD

**Issue by wopian** [wopian/zeepkist-records#169]
This was added as a dependency to speed-up development but have opted to not use any of its components.

Will need to restore client logic that was removed when adding the framework (CSS variables) and some minor layout components for main site structure.

```[tasklist]
### Tasks
- [x] Remove Arco layout components used in App.vue
- [ ] Remove Arco statistics component in Dashboard
- [x] Re-add own CSS variables to root
- [x] Update CSS variable names back to own naming scheme
- [x] Re-add native dark mode media queries
- [ ] Ensure styling is consistent with before
```
