### ISSUE TITLE
Community Events: Zeepkist Showdown

### ISSUE THREAD

**Issue by wopian** [wopian/zeepkist-records#477]
```[tasklist]
### Tasks
- [ ] Add an `events` page for community events
- [ ] Create a section for the `Zeepkist Showdown`
- [ ] Create a view for the Zeepkist Showdown
- [ ] Create a component for generating a tournament bracket
- [ ] Rename and use the `showdown-1.csv` data to populate a tournament bracket
```
